fixed cmake detection in configure Again.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -147,14 +147,29 @@ if [ `which cmake` ]; then
   echo "Testing existing cmake version..."
   currentversion=`cmake --version | tr -dc '[0-9].'`
   echo "Detected $currentversion . Required 2.8.3"
-  check_version "2.8.3" `cmake --version | tr -dc '[0-9].'`
+  check_version "2.8.3" $currentversion
   versionok=$?
   if [ $versionok -eq 1 ]; then
-    echo "CMakeversion is good"
+    echo "CMake version is good"
     CMAKE="cmake"
   fi
 fi
-if [ -z CMAKE -o ! -f $DEPS_PREFIX/bin/cmake ]; then
+
+# CMake not found and there is a cmake in the deps directory!
+if [ -z CMAKE -a -f $DEPS_PREFIX/bin/cmake ]; then 
+  #test cmake version
+  echo "Testing existing cmake version..."
+  currentversion=`$DEPS_PREFIX/bin/cmake --version | tr -dc '[0-9].'`
+  echo "Detected $currentversion . Required 2.8.3"
+  check_version "2.8.3" $currentversion
+  versionok=$?
+  if [ $versionok -eq 1 ]; then
+    echo "CMake version is good"
+    CMAKE="cmake"
+  fi
+fi
+
+if [ -z CMAKE ]; then
   echo "This script will now proceed to download CMake and set it up in"
   echo "the local graphlabapi/deps directory. The GraphLab compilation "
   echo "process will be directed to use graphlabapi/deps/cmake."
